package com.copdhealthtracker.utils

import android.content.Context
import android.content.SharedPreferences
import androidx.preference.PreferenceManager
import com.copdhealthtracker.data.model.*
import com.copdhealthtracker.repository.DataRepository
import kotlinx.coroutines.flow.first
import java.text.SimpleDateFormat
import java.util.Calendar
import java.util.Date
import java.util.Locale

class ReportGenerator(
    private val context: Context,
    private val repository: DataRepository
) {
    private val prefs: SharedPreferences = PreferenceManager.getDefaultSharedPreferences(context)
    private val dateFormat = SimpleDateFormat("MMM d, yyyy", Locale.getDefault())
    private val dateTimeFormat = SimpleDateFormat("MMM d, yyyy 'at' h:mm a", Locale.getDefault())

    suspend fun generateFullReport(): String {
        val sb = StringBuilder()
        
        // Header
        sb.appendLine("========================================")
        sb.appendLine("       COPD FUEL REPORT")
        sb.appendLine("========================================")
        sb.appendLine()
        sb.appendLine("Report Generated: ${dateTimeFormat.format(Date())}")
        sb.appendLine()
        
        // Profile Section
        sb.append(generateProfileSection())
        
        // Severity Assessment Section
        sb.append(generateSeveritySection())
        
        // Exacerbation Plan Section
        sb.append(generateExacerbationPlanSection())
        
        // Medications Section
        sb.append(generateMedicationsSection())
        
        // Tracking Data Section (Last 30 days)
        sb.append(generateTrackingSection())
        
        // Footer
        sb.appendLine()
        sb.appendLine("========================================")
        sb.appendLine("         END OF REPORT")
        sb.appendLine("========================================")
        sb.appendLine()
        sb.appendLine("This report was generated by COPD Fuel.")
        sb.appendLine("Please consult with your healthcare provider for medical advice.")
        
        return sb.toString()
    }

    private fun generateProfileSection(): String {
        val sb = StringBuilder()
        
        sb.appendLine("----------------------------------------")
        sb.appendLine("PATIENT PROFILE")
        sb.appendLine("----------------------------------------")
        sb.appendLine()
        
        // Basic Info
        val age = prefs.getString("age", null)
        val sex = prefs.getString("sex", null)
        val weight = prefs.getString("weight", null)
        val height = prefs.getString("height", null)
        val lastUpdated = prefs.getString("last_updated", null)
        
        sb.appendLine("Age: ${age ?: "Not set"}")
        sb.appendLine("Sex: ${sex ?: "Not set"}")
        sb.appendLine("Weight: ${if (weight.isNullOrEmpty()) "Not set" else "$weight lbs"}")
        sb.appendLine("Height: ${height ?: "Not set"}")
        
        // Calculate BMI
        if (!weight.isNullOrEmpty() && !height.isNullOrEmpty()) {
            val bmi = computeBmi(weight, height)
            sb.appendLine("BMI: ${bmi ?: "N/A"}")
        }
        sb.appendLine()
        
        // Activity Level
        val activityLevel = prefs.getString("activity_level", "")
        val activityText = when (activityLevel) {
            "low" -> "Low activity (limited movement or mostly sedentary)"
            "moderate" -> "Moderate activity (regular daily activities with some exercise)"
            "pulmonary_rehab" -> "Participating in pulmonary rehabilitation"
            "high" -> "High activity (active lifestyle or regular exercise)"
            "exacerbation" -> "Currently experiencing a COPD exacerbation or flare up"
            "kidney_disease" -> "Kidney disease (including chronic kidney disease Stage 2)"
            "dialysis" -> "Currently on dialysis"
            else -> "Not set"
        }
        sb.appendLine("Activity Level: $activityText")
        
        // Protein Target
        val proteinTargetLow = prefs.getInt("protein_target_low", 0)
        val proteinTargetHigh = prefs.getInt("protein_target_high", 0)
        if (proteinTargetLow > 0 && proteinTargetHigh > 0) {
            sb.appendLine("Daily Protein Target: $proteinTargetLow - $proteinTargetHigh g/day")
        }
        sb.appendLine()
        
        // Health Conditions
        sb.appendLine("Health Conditions:")
        val hasKidneyDisease = prefs.getBoolean("condition_kidney_disease", false)
        val hasHighCholesterol = prefs.getBoolean("condition_high_cholesterol", false)
        val hasPulmonaryHypertension = prefs.getBoolean("condition_pulmonary_hypertension", false)
        val hasDialysis = prefs.getBoolean("condition_dialysis", false)
        val hasNone = prefs.getBoolean("condition_none", false)
        val hasOther = prefs.getBoolean("condition_other", false)
        val otherText = prefs.getString("condition_other_text", "")
        
        if (hasNone) {
            sb.appendLine("  - None reported")
        } else {
            if (hasKidneyDisease) sb.appendLine("  - Kidney disease")
            if (hasHighCholesterol) sb.appendLine("  - High cholesterol")
            if (hasPulmonaryHypertension) sb.appendLine("  - Pulmonary hypertension")
            if (hasDialysis) sb.appendLine("  - Currently on dialysis")
            if (hasOther && !otherText.isNullOrEmpty()) sb.appendLine("  - Other: $otherText")
            if (!hasKidneyDisease && !hasHighCholesterol && !hasPulmonaryHypertension && !hasDialysis && !hasOther) {
                sb.appendLine("  - None specified")
            }
        }
        sb.appendLine()
        
        // Oxygen Settings
        val usesOxygen = prefs.getBoolean("uses_oxygen", false)
        sb.appendLine("Supplemental Oxygen: ${if (usesOxygen) "Yes" else "No"}")
        if (usesOxygen) {
            val lpm = prefs.getString("oxygen_lpm", "")
            if (!lpm.isNullOrEmpty()) {
                sb.appendLine("  LPM: $lpm")
            }
        }
        
        // BIPAP Settings
        val usesBipap = prefs.getBoolean("uses_bipap", false)
        sb.appendLine("BIPAP/NIV: ${if (usesBipap) "Yes" else "No"}")
        if (usesBipap) {
            val machineType = prefs.getString("bipap_machine_type", "")
            val bipapSetting = prefs.getString("bipap_setting", "")
            if (!machineType.isNullOrEmpty()) sb.appendLine("  Machine Type: $machineType")
            if (!bipapSetting.isNullOrEmpty()) sb.appendLine("  Setting: $bipapSetting")
        }
        sb.appendLine()
        
        // Contacts
        sb.appendLine("Healthcare Contacts:")
        val doctorName = prefs.getString("doctor_name", "")
        val doctorPhone = prefs.getString("doctor_phone", "")
        val emergencyName = prefs.getString("emergency_contact_name", "")
        val emergencyPhone = prefs.getString("emergency_contact_phone", "")
        
        sb.appendLine("  Doctor: ${if (doctorName.isNullOrEmpty()) "Not set" else doctorName}")
        sb.appendLine("  Doctor Phone: ${if (doctorPhone.isNullOrEmpty()) "Not set" else doctorPhone}")
        sb.appendLine("  Emergency Contact: ${if (emergencyName.isNullOrEmpty()) "Not set" else emergencyName}")
        sb.appendLine("  Emergency Phone: ${if (emergencyPhone.isNullOrEmpty()) "Not set" else emergencyPhone}")
        sb.appendLine()
        
        if (!lastUpdated.isNullOrEmpty()) {
            sb.appendLine("Profile Last Updated: $lastUpdated")
        }
        sb.appendLine()
        
        return sb.toString()
    }

    private fun generateSeveritySection(): String {
        val sb = StringBuilder()
        
        sb.appendLine("----------------------------------------")
        sb.appendLine("COPD SEVERITY ASSESSMENT")
        sb.appendLine("----------------------------------------")
        sb.appendLine()
        
        // Get saved severity assessment data
        val fev1 = prefs.getString("severity_fev1", null)
        val hospitalizations = prefs.getString("severity_hospitalizations", null)
        val exacerbations = prefs.getString("severity_exacerbations", null)
        val usesOxygenSeverity = prefs.getString("severity_oxygen", null)
        val severityResult = prefs.getString("severity_result", null)
        val severityDescription = prefs.getString("severity_description", null)
        val severityDate = prefs.getString("severity_assessment_date", null)
        
        if (severityResult != null) {
            sb.appendLine("Assessment Results:")
            sb.appendLine("  FEV1 Percentage: ${fev1 ?: "Unknown"}")
            sb.appendLine("  Hospitalizations (past year): ${hospitalizations ?: "Unknown"}")
            sb.appendLine("  Exacerbations (past year): ${exacerbations ?: "Unknown"}")
            sb.appendLine("  Uses Supplemental Oxygen: ${usesOxygenSeverity ?: "Unknown"}")
            sb.appendLine()
            sb.appendLine("Severity Level: $severityResult")
            if (!severityDescription.isNullOrEmpty()) {
                sb.appendLine()
                sb.appendLine("Description: $severityDescription")
            }
            if (!severityDate.isNullOrEmpty()) {
                sb.appendLine()
                sb.appendLine("Assessment Date: $severityDate")
            }
        } else {
            sb.appendLine("No severity assessment has been completed.")
            sb.appendLine("Use the Severity Assessment tool in Resources to evaluate your COPD severity.")
        }
        sb.appendLine()
        sb.appendLine("Note: This assessment is for informational purposes only.")
        sb.appendLine("Please consult with your healthcare provider for accurate diagnosis.")
        sb.appendLine()
        
        return sb.toString()
    }

    private fun generateExacerbationPlanSection(): String {
        val sb = StringBuilder()
        
        sb.appendLine("----------------------------------------")
        sb.appendLine("EXACERBATION ACTION PLAN")
        sb.appendLine("----------------------------------------")
        sb.appendLine()
        
        // Additional Instructions from doctor
        val instructions = prefs.getString("action_plan_instructions", "")
        
        // Zone-based action plan
        sb.appendLine("GREEN ZONE - I'm Doing Well:")
        sb.appendLine("Symptoms:")
        sb.appendLine("  - Usual activity and exercise level")
        sb.appendLine("  - Usual amounts of cough and phlegm/mucus")
        sb.appendLine("  - Sleep well at night")
        sb.appendLine("  - Appetite is good")
        sb.appendLine("Action: Take daily medications as prescribed")
        sb.appendLine()
        
        sb.appendLine("YELLOW ZONE - I'm Having a Bad Day:")
        sb.appendLine("Symptoms:")
        sb.appendLine("  - More breathless than usual")
        sb.appendLine("  - Less energy for daily activities")
        sb.appendLine("  - Increased or thicker phlegm/mucus")
        sb.appendLine("  - Using quick relief inhaler/nebulizer more often")
        sb.appendLine("  - Swelling of ankles more than usual")
        sb.appendLine("  - More coughing than usual")
        sb.appendLine("  - Feel like I have a cold")
        sb.appendLine("  - Not sleeping well")
        sb.appendLine("  - Appetite is not good")
        sb.appendLine("Action: Continue daily medication and start exacerbation medications as prescribed")
        sb.appendLine()
        
        sb.appendLine("RED ZONE - I Need Urgent Medical Care:")
        sb.appendLine("Symptoms:")
        sb.appendLine("  - Severe shortness of breath, even at rest")
        sb.appendLine("  - Not able to do any activity because of breathing")
        sb.appendLine("  - Not able to sleep because of breathing")
        sb.appendLine("  - Fever or shaking chills")
        sb.appendLine("  - Feeling confused or very drowsy")
        sb.appendLine("  - Chest pains")
        sb.appendLine("  - Coughing up blood")
        sb.appendLine("Action: Call 911 or have someone take you to the emergency room")
        sb.appendLine()
        
        if (!instructions.isNullOrEmpty()) {
            sb.appendLine("Additional Instructions from Doctor:")
            sb.appendLine(instructions)
            sb.appendLine()
        }
        
        return sb.toString()
    }

    private suspend fun generateMedicationsSection(): String {
        val sb = StringBuilder()
        
        sb.appendLine("----------------------------------------")
        sb.appendLine("MEDICATIONS")
        sb.appendLine("----------------------------------------")
        sb.appendLine()
        
        // Daily Medications
        sb.appendLine("Daily Medications:")
        val dailyMeds = repository.getMedicationsByType("daily").first()
        if (dailyMeds.isEmpty()) {
            sb.appendLine("  No daily medications added")
        } else {
            dailyMeds.forEach { med ->
                sb.appendLine("  - ${med.name}")
                sb.appendLine("    Dosage: ${med.dosage}")
                sb.appendLine("    Frequency: ${med.frequency}")
            }
        }
        sb.appendLine()
        
        // Exacerbation Medications
        sb.appendLine("Exacerbation Medications:")
        val exacerbMeds = repository.getMedicationsByType("exacerbation").first()
        if (exacerbMeds.isEmpty()) {
            sb.appendLine("  No exacerbation medications added")
        } else {
            exacerbMeds.forEach { med ->
                sb.appendLine("  - ${med.name}")
                sb.appendLine("    Dosage: ${med.dosage}")
                sb.appendLine("    Frequency: ${med.frequency}")
            }
        }
        sb.appendLine()
        
        return sb.toString()
    }

    private suspend fun generateTrackingSection(): String {
        val sb = StringBuilder()
        
        sb.appendLine("----------------------------------------")
        sb.appendLine("TRACKING DATA (Last 30 Days)")
        sb.appendLine("----------------------------------------")
        sb.appendLine()
        
        // Calculate date range (last 30 days)
        val calendar = Calendar.getInstance()
        val endDate = calendar.timeInMillis
        calendar.add(Calendar.DAY_OF_YEAR, -30)
        calendar.set(Calendar.HOUR_OF_DAY, 0)
        calendar.set(Calendar.MINUTE, 0)
        calendar.set(Calendar.SECOND, 0)
        calendar.set(Calendar.MILLISECOND, 0)
        val startDate = calendar.timeInMillis
        
        sb.appendLine("Period: ${dateFormat.format(Date(startDate))} - ${dateFormat.format(Date(endDate))}")
        sb.appendLine()
        
        // Nutrition Summary
        sb.append(generateNutritionSummary(startDate, endDate))
        
        // Exercise Summary
        sb.append(generateExerciseSummary(startDate, endDate))
        
        // Oxygen Readings Summary
        sb.append(generateOxygenSummary(startDate, endDate))
        
        // Weight Summary
        sb.append(generateWeightSummary(startDate, endDate))
        
        // Water Intake Summary
        sb.append(generateWaterSummary(startDate, endDate))
        
        return sb.toString()
    }

    private suspend fun generateNutritionSummary(startDate: Long, endDate: Long): String {
        val sb = StringBuilder()
        
        sb.appendLine("NUTRITION SUMMARY:")
        
        val foods = repository.getFoodsByDateRange(startDate, endDate).first()
        
        if (foods.isEmpty()) {
            sb.appendLine("  No food entries recorded in this period.")
            sb.appendLine()
            return sb.toString()
        }
        
        // Group by date and calculate daily averages
        val groupedByDate = foods.groupBy { 
            val cal = Calendar.getInstance()
            cal.timeInMillis = it.date
            cal.set(Calendar.HOUR_OF_DAY, 0)
            cal.set(Calendar.MINUTE, 0)
            cal.set(Calendar.SECOND, 0)
            cal.set(Calendar.MILLISECOND, 0)
            cal.timeInMillis
        }
        
        val daysLogged = groupedByDate.size
        
        // Calculate totals and averages
        var totalCalories = 0.0
        var totalProtein = 0.0
        var totalCarbs = 0.0
        var totalFat = 0.0
        var totalFiber = 0.0
        var totalSodium = 0.0
        var totalPotassium = 0.0
        var totalWater = 0.0
        
        foods.forEach { food ->
            totalCalories += food.calories
            totalProtein += food.protein
            totalCarbs += food.carbs
            totalFat += food.fat
            totalFiber += food.fiber
            totalSodium += food.sodium
            totalPotassium += food.potassium
            totalWater += food.water
        }
        
        sb.appendLine("  Days Logged: $daysLogged")
        sb.appendLine("  Total Entries: ${foods.size}")
        sb.appendLine()
        sb.appendLine("  Daily Averages:")
        sb.appendLine("    Calories: ${String.format("%.0f", totalCalories / daysLogged)} kcal")
        sb.appendLine("    Protein: ${String.format("%.1f", totalProtein / daysLogged)} g")
        sb.appendLine("    Carbohydrates: ${String.format("%.1f", totalCarbs / daysLogged)} g")
        sb.appendLine("    Fat: ${String.format("%.1f", totalFat / daysLogged)} g")
        sb.appendLine("    Fiber: ${String.format("%.1f", totalFiber / daysLogged)} g")
        sb.appendLine("    Sodium: ${String.format("%.0f", totalSodium / daysLogged)} mg")
        sb.appendLine("    Potassium: ${String.format("%.0f", totalPotassium / daysLogged)} mg")
        sb.appendLine("    Water: ${String.format("%.1f", totalWater / daysLogged)} oz")
        sb.appendLine()
        
        // Protein target comparison
        val proteinTarget = prefs.getFloat("protein_target", 0f)
        if (proteinTarget > 0) {
            val avgProtein = totalProtein / daysLogged
            val percentOfTarget = (avgProtein / proteinTarget) * 100
            sb.appendLine("  Protein Target Progress:")
            sb.appendLine("    Daily Target: ${proteinTarget.toInt()} g")
            sb.appendLine("    Average Intake: ${String.format("%.1f", avgProtein)} g")
            sb.appendLine("    Achievement: ${String.format("%.0f", percentOfTarget)}% of target")
            sb.appendLine()
        }
        
        return sb.toString()
    }

    private suspend fun generateExerciseSummary(startDate: Long, endDate: Long): String {
        val sb = StringBuilder()
        
        sb.appendLine("EXERCISE SUMMARY:")
        
        val exercises = repository.getExercisesByDateRange(startDate, endDate).first()
        
        if (exercises.isEmpty()) {
            sb.appendLine("  No exercise entries recorded in this period.")
            sb.appendLine()
            return sb.toString()
        }
        
        // Group by type
        val byType = exercises.groupBy { it.type }
        val totalMinutes = exercises.sumOf { it.minutes }
        val daysExercised = exercises.map { 
            val cal = Calendar.getInstance()
            cal.timeInMillis = it.date
            cal.set(Calendar.HOUR_OF_DAY, 0)
            cal.set(Calendar.MINUTE, 0)
            cal.set(Calendar.SECOND, 0)
            cal.set(Calendar.MILLISECOND, 0)
            cal.timeInMillis
        }.distinct().size
        
        sb.appendLine("  Total Exercise Sessions: ${exercises.size}")
        sb.appendLine("  Days with Exercise: $daysExercised")
        sb.appendLine("  Total Minutes: $totalMinutes")
        sb.appendLine("  Average per Session: ${String.format("%.1f", totalMinutes.toDouble() / exercises.size)} minutes")
        sb.appendLine()
        sb.appendLine("  By Exercise Type:")
        byType.forEach { (type, entries) ->
            val typeMinutes = entries.sumOf { it.minutes }
            sb.appendLine("    $type: ${entries.size} sessions, $typeMinutes minutes total")
        }
        sb.appendLine()
        
        return sb.toString()
    }

    private suspend fun generateOxygenSummary(startDate: Long, endDate: Long): String {
        val sb = StringBuilder()
        
        sb.appendLine("OXYGEN READINGS SUMMARY:")
        
        val readings = repository.getOxygenReadingsByDateRange(startDate, endDate).first()
        
        if (readings.isEmpty()) {
            sb.appendLine("  No oxygen readings recorded in this period.")
            sb.appendLine()
            return sb.toString()
        }
        
        val levels = readings.map { it.level }
        val avgLevel = levels.average()
        val minLevel = levels.minOrNull() ?: 0
        val maxLevel = levels.maxOrNull() ?: 0
        
        sb.appendLine("  Total Readings: ${readings.size}")
        sb.appendLine("  Average Level: ${String.format("%.1f", avgLevel)}%")
        sb.appendLine("  Minimum Level: $minLevel%")
        sb.appendLine("  Maximum Level: $maxLevel%")
        
        // Count readings by range
        val below88 = levels.count { it < 88 }
        val between88and92 = levels.count { it in 88..92 }
        val above92 = levels.count { it > 92 }
        
        sb.appendLine()
        sb.appendLine("  Distribution:")
        sb.appendLine("    Below 88% (Critical): $below88 readings")
        sb.appendLine("    88-92% (Low Normal): $between88and92 readings")
        sb.appendLine("    Above 92% (Normal): $above92 readings")
        sb.appendLine()
        
        return sb.toString()
    }

    private suspend fun generateWeightSummary(startDate: Long, endDate: Long): String {
        val sb = StringBuilder()
        
        sb.appendLine("WEIGHT SUMMARY:")
        
        val weights = repository.getWeightsByDateRange(startDate, endDate).first()
            .filter { !it.isGoal }
        
        if (weights.isEmpty()) {
            sb.appendLine("  No weight entries recorded in this period.")
            sb.appendLine()
            return sb.toString()
        }
        
        val sortedWeights = weights.sortedBy { it.date }
        val startWeight = sortedWeights.first().weight
        val endWeight = sortedWeights.last().weight
        val change = endWeight - startWeight
        
        sb.appendLine("  Entries Recorded: ${weights.size}")
        sb.appendLine("  Starting Weight: ${String.format("%.1f", startWeight)} lbs")
        sb.appendLine("  Current Weight: ${String.format("%.1f", endWeight)} lbs")
        sb.appendLine("  Change: ${if (change >= 0) "+" else ""}${String.format("%.1f", change)} lbs")
        
        // Goal weight comparison
        val goalWeight = repository.getGoalWeight().first()
        if (goalWeight != null) {
            val toGoal = endWeight - goalWeight.weight
            sb.appendLine("  Goal Weight: ${String.format("%.1f", goalWeight.weight)} lbs")
            sb.appendLine("  Distance to Goal: ${String.format("%.1f", kotlin.math.abs(toGoal))} lbs ${if (toGoal > 0) "to lose" else if (toGoal < 0) "to gain" else "(at goal)"}")
        }
        sb.appendLine()
        
        return sb.toString()
    }

    private suspend fun generateWaterSummary(startDate: Long, endDate: Long): String {
        val sb = StringBuilder()
        
        sb.appendLine("WATER INTAKE SUMMARY:")
        
        val waterEntries = repository.getWaterEntriesByDateRange(startDate, endDate).first()
        
        if (waterEntries.isEmpty()) {
            sb.appendLine("  No water intake recorded in this period.")
            sb.appendLine()
            return sb.toString()
        }
        
        // Group by date
        val groupedByDate = waterEntries.groupBy { 
            val cal = Calendar.getInstance()
            cal.timeInMillis = it.date
            cal.set(Calendar.HOUR_OF_DAY, 0)
            cal.set(Calendar.MINUTE, 0)
            cal.set(Calendar.SECOND, 0)
            cal.set(Calendar.MILLISECOND, 0)
            cal.timeInMillis
        }
        
        val daysTracked = groupedByDate.size
        val totalOz = waterEntries.sumOf { it.amount }
        val avgDailyOz = if (daysTracked > 0) totalOz / daysTracked else 0
        val goalOz = 64 // 8 cups per day
        val daysMetGoal = groupedByDate.count { (_, entries) -> entries.sumOf { it.amount } >= goalOz }
        
        sb.appendLine("  Days Tracked: $daysTracked")
        sb.appendLine("  Total Intake: $totalOz oz")
        sb.appendLine("  Daily Average: $avgDailyOz oz")
        sb.appendLine("  Daily Goal: $goalOz oz")
        sb.appendLine("  Days Goal Met: $daysMetGoal / $daysTracked")
        sb.appendLine()
        
        return sb.toString()
    }

    private fun computeBmi(weightStr: String?, heightStr: String?): String? {
        if (weightStr.isNullOrEmpty() || heightStr.isNullOrEmpty()) return null
        val weightLbs = weightStr.toDoubleOrNull() ?: return null
        if (weightLbs <= 0) return null
        val heightInches = parseHeightToInches(heightStr) ?: return null
        if (heightInches <= 0) return null
        val bmi = (weightLbs / (heightInches * heightInches)) * 703
        return String.format(Locale.getDefault(), "%.1f", bmi)
    }

    private fun parseHeightToInches(s: String): Double? {
        val t = s.trim()
        if (t.isEmpty()) return null
        val numbers = t.split(Regex("[^0-9.]+")).filter { it.isNotEmpty() }.mapNotNull { it.toDoubleOrNull() }
        if (numbers.size >= 2) return numbers[0] * 12 + numbers[1]
        if (numbers.size == 1) return if (numbers[0] < 25) numbers[0] * 12 else numbers[0]
        return null
    }
}
